name: ligo
dependencies:
    - python=3.9
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.55.4
    - h5py==3.12.1
    - kiwisolver==1.4.7
    - matplotlib==3.9.4
    - numpy==2.0.2
    - pillow==11.1.0
    - pyparsing==3.2.1
    - scipy==1.13.1
    - ipykernel
